### ISSUE TITLE
Typo in app.js file

### ISSUE THREAD

**Issue by moonman369** [eduladder/eladrProtocolBackend#9]
The `app.js` file should import Sequelize Model Constructor, `videoandmeta` from the file `models/videometa.js`. 
On the other hand, `app.js` imports `videometa` as the Model Constructor. This typo causes problems when sending `/database`, `/files` and `/search` requests to the app.

**Comment by arunwebber** [comment]
This is fixed https://github.com/eduladder/eladrProtocolBackend/pull/14
